export const encodedKey = "QUl6YVN5RGJJMUFJUERETFdhY0tvbGFFZlRKWkJKbi1sdkhnYVdn"
export const mapboxToken = "pk.eyJ1Ijoia2V2YW5kbyIsImEiOiJjaXphYnRnM3owMm1vMnFvOHFiYm5ibm5jIn0.sY29SXbpr7W9eQHiwpqAwg"
